name: DevSecOps CI

on:
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write 

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest

      - name: Lint with pylint
        run: pylint app/ tests/

      - name: Run tests
        run: PYTHONPATH=. pytest

      - name: Build Docker image
        run: |
          docker build -t devsecops-fastapi-app:latest .
      
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-fastapi-app:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
  
      - name: Tag and push image to Artifact Registry
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO_NAME }}/devsecops-fastapi-app:${{ github.sha }}"
          docker tag devsecops-fastapi-app:latest $IMAGE
          docker push $IMAGE

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Create terraform.tfvars from secrets
        run: |
          echo 'project_id = "${{ secrets.GCP_PROJECT_ID }}"' > terraform/terraform.tfvars
          echo 'region     = "${{ secrets.GCP_REGION }}"' >> terraform/terraform.tfvars
          echo 'repo_name  = "${{ secrets.GCP_ARTIFACT_REPO_NAME }}"' >> terraform/terraform.tfvars

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var-file=terraform.tfvars
      
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials fastapi-cluster \
            --region ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Replace image reference in deployment.yaml
        run: |
          sed -i "s|<IMAGE_PLACEHOLDER>|${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO_NAME }}/devsecops-fastapi-app:${{ github.sha }}|" k8s/deployment.yaml

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

